nginx:
  name: nginx-proxy
  labels:
    id: c0929678
    app: wordpress
    env: dev
  image:
    repository: kishna/new-nginx-image
    tag: v1
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    type: NodePort
    port: 80
    targetPort: 80