wp:
  name: wpapp
  labels:
    id: c0929678
    app: wpapp
    env: dev
    stack: wordpress
  image:
    repository: wordpress
    tag: latest
    pullPolicy: Always
  replicas: 5
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  resources:
    requests:
      cpu: "150m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"
  configmap:
    ## KEY: "value"
    WORDPRESS_DB_HOST: "wp-database.dbname.svc.cluster.local:3306"
    WORDPRESS_DB_USER: 3324_user
    WORDPRESS_DB_NAME: c0929678
    APP_ENV: dev
  containerPorts:
      http: 80
